- javascript/BinarySearch.js
Binary Search in JavaScript for #1 
---
Go implementation already exists
> Binary Search in JavaScript

- javascript/LinkedList.js
Added Linked List DSA in JavaScript #1
> Linked List

- javascript/BubbleSort.js
+ Added Bubble sort with the help of JavaScript
Ref #1
> Bubble Sort

- javascript/MergeSort.js
> add MergeSort.js

- README.md
- rust/BubbleSort.rs
I added bubble sort written in Rust
> Added bubble sort implemented in Rust

- java/LinearSearch.java
- java/SelectionSort.java
**Linear Search Using _Java**_
> Linear Searching

- rust/Stack.rs
I added Stack implementation written in Rust
> Stack implementation in Rust

- rust/Queue.rs
I added Queue implementation written in Rust
> Queue implementation in Rust

- cpp/Number_of_island
> Island problem leetcode dfs

- python/MergeSort.py
- python/Untitled Document 1
> Added merge sort implemented in python

- .github/workflows/main.yml
- README.md
This PR utilizes GitHub Actions and GitHub API to update the languages listed in the README whenever a push is made to `master`.
> Automate README.md updation using GitHub Actions

- python/BubbleSort.py
Added bubble sort implementation in python
Ref : #1
> Python : Bubble Sort

- README.md
- javascript/InsertionSort.js
- javascript/Stack.js
Implemented insertion sort in javascript
Ref : #1
> Insertion Sort

- javascript/SelectionSort.js
Implemented Selection Sort in JavaScript
Ref : #1
> Added Selection Sort

- csharp/Selectionsort.cs
Pulled the files to see whats inside, saw the C# folder and made SelectionSort for it even though it wasn't on the actual readme? 
Happy hacking!
- Joonas
> Selection sort for C#

- javascript/LinearSearch.js
> Linear Search

- csharp/BubbleSort.cs
Didn't find anything suitable for my beginner level in the hacktober repositories, so I spent some time figuring out C# and BubbleSort :)
> Added BubbleSort for c#

- python/BinarySearch.py
Implemented Binary Search in Python
Ref #1
> Binary Search

- python/selectionSort.py
> Add selectionSort.py into python code directory

- java/BubbleSort.java
- python/LinearSearch.py
Implemented Linear search using python
Ref #1
> Python: Linear Search

- cpp/selectionSort.cpp
I've done selection sort in C++.
> selectionSort in Cpp

- python/breadthFirstSearch.py
- python/depthFirstSearch.py
> Added 2 files in (python/). [BFS & DFS]

- java/shellSort.java
Created an Shell Sort in Java.
> shellSort.java

- python/bucketSort.py
Creating an Bucket Sort in Python.
> bucketSort.py

- java/quickSort.java
> quickSort.java

- cpp/addMatrix.cpp
C++ Program of Adding Two Matrix Using Multi-dimensional Arrays
> addMatrix.cpp

- cpp/selectionsSort.cpp
added selection sort in c++ folder.
> selectionsSort.cpp

- c/selectionSort.c
added selection sort in c folder.
> selectionSort

- c/bubbleSort.c
> Added C Bubble Sort

- README.md
Changed table to more readable format, and sorted algorithms in alphabetical order.
> Feat: Improved README

- c/Stack.c
> Stack implementation using Array in C .

- c/LinkedList.c
Added a topic related to Linked List in C language ! #1
> C program to create and sort a single Linked List.

- golang/Palindrome.go
Program Name - "Palindrome.go"
Checks completed(self-Check)
-  File added in proper folder
-  File name is CamelCase
-  Proper commenting done
-  Clean code
-  I have performed a self-review of my own code
> add: palindrome series in golang

- golang/quickSort.go
Program Name - "quickSort.go"
Checks completed(self-Check)
- File added in proper folder
- File name is camelCase
- Proper commenting done
- Clean code
- I have performed a self-review of my own code
> Golang Implementation of QuickSort

- README.md
- c/tower-of-hanoi.c
hope i was helpful , hoping you accept my PR as soon as possible so that i can go for more PR's
> added readme and an tower of hanoi problem
